/**
THIS FILE TRYIES THE SOLUTION OF CORMAN PROBLEM.
*/

/**
Q. (9.3-7)

SOL: 1.WE NEED TO FIND THE MEDIAN IN O(N).
     2. AFTER FINDING MEDIAN WE KEP ANOTHER ARRAY , AND KEEY THE ABS(A[I]-MEDIAN) FOR EACH ELEMENT
       OF THE ARRAY.
     3. AFTER THAT WE WOULD FIND THE KTH-ORDER STATIC IN THIS NEW ARRAY.
     4. AFTER FINDING THIS WE, WOULD TRAVERSE THE DEFERENCE, ARRAY AND KEEP ALL THE ELEMENTS
       SMALLER THAN KTH-ORDER STATICS.
     5. THIS NEW ARRAY WOULD CONTAIN THE ALL ELEMENTS , THAT ARE K-CLOSER TO THE MEDIAN OF THE ARRAY.
*/

/**
Q. (9.3-4)

SOL:  1. WE WOULD FIND THE iTH-SMALLEST, USING QUICKSORT PARTITION, WHEN WE WOULD FIND THE iTH-
         ORDERSTATIC THROUGH THIS, ALGORITHM THEN (i-1) ELEMENTS LEFT TO THIS WOULD BE SMALLER
         THAN THIS ELEMENT AND (N-I) ELEMENTS, RIGHT TO THIS WOULD BE GREATER THAN THIS.
*/

/**
q.  (9.3-6)
    The kth quantiles of an n-element set are the k - 1 order statistics that divide the sorted set into k
    equal-sized sets (to within 1). Give an O(n lg k)-time algorithm to list the kth quantiles of a set.

SOL:
*/

/**
Q. (9.3-8)

SOL:
*/
