/**
http://www.codechef.com/problems/CIELNUM1
*/

/**
NOTE:
		IF NO. OF DIGITS IN THE NUMBER ARE N.
		THEN TOTAL NUMBER OF CIEL NUMBERS ARE:- 3^N.
												3*3*3*.........*3(n TIMES, SINCE FOR EACH POSITION THERE ARE THREE POSSIBLE WAY TO PLACE
												THE INTEGER 3,5,OR 8).
		SO FINDING THE CIEL NO. WE NEED TO PLACE THE EACH DIGIT TO THE CORRECT PLACE AND AFTER THAT WE NEED TO CHECK THE 
		CRITERIA OF CIEL NO. AS D(K,8)>=D(K,5)>=D(K,3).
		FOR THAT WE WOULD USE ANOTHER ARRAY FOR STORIN GTH ENO OF 3'S,5'S AND 8'S, IN ANY INTEGER. AND FOR THE NUMBER
		WE WOULD KEEP ANOTHER ARRAY FOR KEEPING THE NUMBER ACCORDING TO THE POSITIONAL PURMUTAION OF 3,5,8.
		WE WOULD EACH NUMBER FROM THE NUMBER ARRAY, AND CHECK THE CIEL CONSTRAINT FROM THE THREE AUXILARY ARRAY.
		IF IT'S SATISFING THE CONDITION THEM WE WOULDL STORE THAT IN THE RESULT ARRAY.
*/

#include<cstdio>
#include<cmath>
#include<cstring>
#include <iostream>
using namespace std;

//int  main
void driver()
{
	printf("\nciel one is running.\n");

	//return 0;
}
